{
    "name": "Base API",
    "summary": "Basic function and methods of API",
    "category": "Hidden",
    "version": "14.0.1.0.1",
    "application": False,
    "author": "",
    "support": "",
    "website": "",
    "license": "LGPL-3",
    "depends": [],
    "external_dependencies": {"python": [], "bin": []},
    "data": [],
    "demo": [],
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
